# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Monkey.D"
description: > # this means to ignore newlines until "email:"
  안녕하세요! Developer Monkey.D 입니다. 
  개발이 힘들어도 포기하지 마세요.
  할 수가 없었기 때문에 포기한게 아니라 포기했기 때문에 할 수 없었던 것입니다. :)

email: a-mail@mail.mail

#로고사진
logo: "/assets/images/logo.JPG"
float_logo: true # true, false (default)

#커버사진
cover: "커버사진경로"

name: 'Dirk Fabisch'
author: 'Dirk Fabisch'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dirkfabisch
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dirkfabisch
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
